'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimesheetApproval.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Report xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        '''  &lt;DataSources&gt;
        '''    &lt;DataSource Name=&quot;ApplicationDataSet&quot;&gt;
        '''      &lt;ConnectionProperties&gt;
        '''        &lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        '''        &lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        '''      &lt;/ConnectionProperties&gt;
        '''      &lt;rd:DataSourceID&gt;44a8df20-fd06-4c5e-bd86-1570488017d4&lt;/r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Automation() As String
            Get
                Return ResourceManager.GetString("Automation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Report xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        '''  &lt;DataSources&gt;
        '''    &lt;DataSource Name=&quot;ApplicationDataSet&quot;&gt;
        '''      &lt;ConnectionProperties&gt;
        '''        &lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        '''        &lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        '''      &lt;/ConnectionProperties&gt;
        '''      &lt;rd:DataSourceID&gt;36d5c46c-c59a-4cf3-96b6-c9a7d1947abf&lt;/r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PendingManHour() As String
            Get
                Return ResourceManager.GetString("PendingManHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Report xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        '''  &lt;DataSources&gt;
        '''    &lt;DataSource Name=&quot;ApplicationDataSet&quot;&gt;
        '''      &lt;ConnectionProperties&gt;
        '''        &lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        '''        &lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        '''      &lt;/ConnectionProperties&gt;
        '''      &lt;rd:DataSourceID&gt;9a68cd4e-067c-40b2-a2f7-90c37a1da183&lt;/r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TimesheetDefault() As String
            Get
                Return ResourceManager.GetString("TimesheetDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Report xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        '''  &lt;DataSources&gt;
        '''    &lt;DataSource Name=&quot;ApplicationDataSet&quot;&gt;
        '''      &lt;ConnectionProperties&gt;
        '''        &lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        '''        &lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        '''      &lt;/ConnectionProperties&gt;
        '''      &lt;rd:DataSourceID&gt;e96b3ac8-148a-4cce-be40-c2f5ace26bdf&lt;/r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TimesheetDefaultCostCTRCodeGrouping() As String
            Get
                Return ResourceManager.GetString("TimesheetDefaultCostCTRCodeGrouping", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
